# application-local.yml

# 각 Profile의 변수
variable:
  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://${variable.eureka.instance.hostname}:${server.port}/eureka

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0    # 개발 환경에서 서비스가 빠르게 등록/해제되도록 설정 (운영시는 주의)
    enable-self-preservation: false       # 자기 보호 모드 비활성화 (빨간 경고 문구 제거)
    eviction-interval-timer-in-ms: 10000  # 서비스가 해제되었을 때 목록에서 제거하는 스캔 주기 (단위: ms, 기본 60초)
